language: kotlin

before_script:
  - chmod +x gradlew
script:
  - gradle check
  - gradle build
  - gradle test
  - gradle codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
