language: kotlin

notifications:
  email: false

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew build
  - ./gradlew test
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
